# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: drt_development
  pool: 5
  username: alishanladhani	
  password: 	

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: drt_test
  pool: 5
  username: alishanladhani
  password: 	

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: drt_production
  pool: 5
  username: alishanladhani
  password: 	
